#!/bin/bash

set -e

log() { echo "`date`: $1"; }

export SPLUNK_USER=splunk
export SPLUNK_BIN=/opt/splunk/bin/splunk
export SPLUNK_HOME=/opt/splunk

# Download & install Splunk Enterprise
if [ ! -d "$SPLUNK_HOME" ]; then 
  wget -O ${SPLUNK_PACKAGE_NAME} "${SPLUNK_PACKAGE_URL}"
  tar xvfz ${SPLUNK_PACKAGE_NAME}
  mv splunk $SPLUNK_HOME
  rm ${SPLUNK_PACKAGE_NAME}
fi

# Create Splunk system user, and set directory permissions
if ! id name >/dev/null 2>&1; then
  useradd -r -s /usr/sbin/nologin -U $SPLUNK_USER
fi
chown -R $SPLUNK_USER:$SPLUNK_USER $SPLUNK_HOME

# Set Splunk admin password and disable first-time run password prompt
cat >>$SPLUNK_HOME/etc/system/local/user-seed.conf <<end
[user_info]
USERNAME = admin
PASSWORD = ${SPLUNK_ADMIN_PASSWORD}
end
touch $SPLUNK_HOME/etc/.ui_login

# Configure systemd to start Splunk at boot
cd /opt/splunk
bin/splunk enable boot-start -user $SPLUNK_USER --accept-license

# Update systemd unit file to ensure graceful shutdown
sed -ie '/^ExecStart=/a KillMode=mixed\nKillSignal=SIGINT\nTimeoutStopSec=10min' /etc/systemd/system/Splunkd.service
sudo systemctl daemon-reload

# Configure Splunk before starting service
# Increase splunkweb connection timeout with splunkd
mkdir -p $SPLUNK_HOME/etc/apps/base-autogenerated/local
cat >>$SPLUNK_HOME/etc/apps/base-autogenerated/local/web.conf <<end
[settings]
splunkdConnectionTimeout = 300
end

chown -R $SPLUNK_USER:$SPLUNK_USER $SPLUNK_HOME/etc/apps/base-autogenerated

# Start Splunk service
sudo systemctl start Splunkd
